### ISSUE TITLE
Dimensional Tears Texture broken

### ISSUE THREAD

**Issue by Lucas-Carrarini** [AstralOrdana/Spelunkery#222] opened 2024-05-17 11:36 UTC
**Describe the bug:**
I found some pools in the End of the Dimensional Tears liquid and in some corners the texture is broken

![image](https://github.com/AstralOrdana/Spelunkery/assets/118176540/de68e7d4-ad44-4212-a840-4e384478575c)

**Versions:**
Minecraft version: 1.20.1
Spelunkery version: 1.20.1-0.3.5
Moonlight Lib version: 1.20-2.11.19
Supplementaries version: 1.20-2.8.11
Fabric API / QSL / Forge version: Forge 47.2.32

**Other mods:**
![image](https://github.com/AstralOrdana/Spelunkery/assets/118176540/c865168f-efc0-4322-bd50-e1448f42f851)

**Textures:**
![image](https://github.com/AstralOrdana/Spelunkery/assets/118176540/8f792b66-8b18-41f0-87d7-08d9746034cd)

**I'M NOT USING SHADERS**

**Logs:**
[latest.log](https://github.com/AstralOrdana/Spelunkery/files/15348517/latest.log)

**To Reproduce:**

1. Load the mods and textures
2. Go to The End

**Expected behavior:**
The dimensional tears pools have some textures broken

**Screenshots:**
![image](https://github.com/AstralOrdana/Spelunkery/assets/118176540/32273b0e-e05f-4b2b-8dda-de948f11f204)

![image](https://github.com/AstralOrdana/Spelunkery/assets/118176540/879c9120-ab86-43fe-9900-22744f77e17f)

**Comment by mintynoura** [comment] 2024-05-24 06:03
i think this is fixed in dev? it was an iris/oculus bug iirc

**Comment by AstralOrdana** [comment] 2024-05-24 06:04
yet another duplicate of https://github.com/AstralOrdana/Spelunkery/issues/135

**Closed as completed by AstralOrdana** 2024-05-24 06:04 UTC
