### ISSUE TITLE
can't get any item or block in sulvival while the mod applied

### ISSUE THREAD

**Issue by mangotastejuice** [AstralOrdana/Spelunkery#95] opened 2023-07-25 02:24 UTC
**Describe the bug:**
A clear and concise description of what the bug is. Include as much information as you can. Images are often helpful, especially screenshots of the F3 debug menu.
https://streamable.com/gcpfjw

short vid that prove a point

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: 0.3.0 forge
Moonlight Lib version: 2.7.2 forge
Fabric API / QSL / Forge version: forge 47.1.43

**Other mods:**
List all mods that you're using; could be in the form of a list of the filenames, a crash report list, a screenshot of
the mods folder, etc. Just make sure all mods used are known!
![화면 캡처 2023-07-25 111648](https://github.com/AstralOrdana/Spelunkery/assets/140468922/07fb703b-5326-46f5-8d5b-20106e16c093)

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
From .minecraft/logs :  "latest.log" as well as "debug.log" if it exists. From .minecraft : "launcher_log" as well as a
file that starts with "hs_err" if it exists. Note: Double check that the logs are from the correct time. ex, don't give
us a log from a month ago because you forgot to check the date.

the game didn't crash

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1.turn on survival mod
2.try to break block or kill mob
3.that's it

**Expected behavior:**

can't get any item or block in sulvival while the mod applied

**Screenshots:**
If applicable, add screenshots to help explain your problem. https://screenshot.help/

I think video will enough.

**Additional info:**
Add any other information that might be needed.

**Comment by AstralOrdana** [comment] 2023-07-25 02:28
duplicate of known issue #92

**Closed by AstralOrdana** 2023-07-25 02:28 UTC
