### ISSUE TITLE
Item duplication bug with Ensorcelattion mod when Spelunkery is installed

### ISSUE THREAD

**Issue by AikaBack** [AstralOrdana/Spelunkery#177] opened 2024-02-06 18:44 UTC
**Describe the bug:**
Spelunkery mod is causing Ensorcellation mod's Soulbound enchantment's items to duplicate on death. Removing spelunkery mod makes enchantment work as intended.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: spelunkery-1.20.1-0.3.5-forge
Moonlight Lib version: moonlight-1.20-2.9.7-forge
Fabric API / QSL / Forge version: forge-47.2.20

**Other mods:**
ensorcellation-1.20.1-5.0.0.21
cofh_core-1.20.1-11.0.0.51
**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
From .minecraft/logs :  "latest.log" as well as "debug.log" if it exists. From .minecraft : "launcher_log" as well as a
file that starts with "hs_err" if it exists. Note: Double check that the logs are from the correct time. ex, don't give
us a log from a month ago because you forgot to check the date.

**To Reproduce:**
1. Install Both spelunkery and Ensorcellation.
2. Make new world, enchant any tool with Soulbound enchantment from Ensorcellation.
3. Die with item in inventory.
4. After death you keep double amount of items enchanted with Soulbound.
**Expected behavior:**
No duplicated items.

**Comment by KingLemming** [comment] 2024-02-06 18:55
Gonna be honest, I don't think either mod causes it. It might be Moonlight Lib or Supplementaries though, if they are also doing things with Player events.

**Comment by AstralOrdana** [comment] 2024-02-06 18:57
that seems likely to me too since spelunkery uses moonlight for its keep-after-death shenanigans

**Comment by SiverDX** [comment] 2024-02-06 19:13
mentioned this in a previous issue already but it's caused by https://github.com/AstralOrdana/Spelunkery/blob/1.20.1/common/src/main/java/com/ordana/spelunkery/mixins/ServerPlayerMixin.java

you don't need this mixin since you're using the moonlight event 

I removed it in the 1.19.2 version

**Comment by AstralOrdana** [comment] 2024-08-12 02:36
fixed in 0.3.6

**Closed as completed by AstralOrdana** 2024-08-12 02:36 UTC
Labels: Fixed but unreleased
