### ISSUE TITLE
Spring Water self replicating

### ISSUE THREAD

**Issue by ShikiTochi** [AstralOrdana/Spelunkery#166] opened 2024-01-21 05:39 UTC
**Describe the bug:**
When finding naturally spawning spring water and or placing a source of it from a bucket it seems to self replicate flowing upwards into the sky making source blocks from itself and also phasing through existing blocks

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version:1.20.1
Spelunkery version:1.20.1-0.3.5
Moonlight Lib version:1.20-2.8.84
Fabric API / QSL / Forge version:47.2.19

**Other mods:**
- adchimneys 10.1.4.0
	- adlods 8.1.0.0
	- aether 1.20.1-1.1.0-neoforge
	- aiimprovements 0.5.2
	- alexscaves 1.0.9
	- alexsmobs 1.22.7
	- allarrowsinfinityfix 1.5
	- alternate_current 1.7.0
	- ambientsounds 5.3.5
	- amplifiednether 1.2.4
	- animal_feeding_trough 1.0.3+1.20.1-forge
	- anvilrestoration 2.2
	- apotheosis 7.2.2
	- apothiccurios 1.0.3
	- appleskin 2.5.1+mc1.20.1
	- aquaculture 2.5.1
	- aquamirae 6.API15
	- architectury 9.1.12
	- ars_artifice 1.20.1-2.0.4
	- ars_creo 4.0.1
	- ars_elemental 1.20.1-0.6.4.0
	- ars_instrumentum 0.0NONE
	- ars_nouveau 4.9.0
	- ars_scalaes 1.20.1-1.10.1-alpha
	- artifacts 9.2.0
	- athena 3.1.1
	- attributefix 21.0.4
	- attributeslib 1.2.1
	- badmobs 19.0.2
	- badpackets 0.4.3
	- balanced_crates 1.7.7
	- balm 7.2.1
	- beautify 2.0.2
	- bedbenefits 13.0.2
	- bellsandwhistles 0.4.3-1.20.x
	- better_arrow_recipe 1.0.0
	- betteradvancements 0.3.2.161
	- bettercombat 1.8.1+1.20.1
	- betterdeserttemples 1.20-Forge-3.0.3
	- betterdogs_dtn 1.2.1
	- betterdungeons 1.20-Forge-4.0.3
	- betterfortresses 1.20-Forge-2.0.5
	- betterfpsdist 1.20.1-4.1
	- betterinvisibility 1.0.4
	- bettermineshafts 1.20-Forge-4.0.4
	- betteroceanmonuments 1.20-Forge-3.0.4
	- bettersafebed 1.20-9
	- betterstrongholds 1.20-Forge-4.0.3
	- betterwitchhuts 1.20-Forge-3.0.3
	- blasting_smelting_raw_metals_ol 1.0.3
	- blockrunner 8.0.2
	- blockui 1.20.1-0.0.98-ALPHA
	- blue_skies 1.3.31
	- bookshelf 20.1.8
	- born_in_chaos_v1 1.0.0
	- bountiful 6.0.3+1.20.1
	- bowinfinityfix 2.6.0
	- brutalbosses 1.20.1-6.6
	- caelus 3.1.0+1.20
	- carryon 2.1.2.7
	- cat_jam 1.2.1
	- cataclysm 1.0
	- cataclysmiccombat 1.2
	- chalk 1.6.3
	- chipped 3.0.1
	- chiselsandbits 1.4.145
	- chunksending 1.20.1-2.8
	- chunky 1.3.92
	- citadel 2.4.9
	- clayblasting 1.19-0
	- clientcrafting 1.20.1-1.7
	- cloth_config 11.1.118
	- clumps 12.0.0.3
	- collective 7.30
	- combatroll 1.3.1+1.20.1
	- comforts 6.3.4+1.20.1
	- commongroovylibrary 0.3.3
	- companion 5.0.1
	- connectedglass 1.1.11
	- connectivity 1.20.1-4.9
	- constructionwand 1.20.1-2.11
	- controlling 12.0.2
	- coroutil 1.20.1-1.3.6
	- cosmeticarmorreworked 1.20.1-v1a
	- cpm 0.6.14a
	- create 0.5.1.f
	- create_confectionery 1.1.0
	- create_crush_everything 1.0.2
	- create_dragon_lib 1.3.3
	- create_enchantment_industry 1.2.7.h
	- create_sa 2.0.4.
	- createaddition 1.20.1-1.2.1
	- createcasing 1.20.1-1.5.0-ht3
	- createdeco 2.0.0-forge-1.20.1
	- createdieselgenerators 1.20.1-1.2f
	- creategbd 1.2.9.1b-1.20.1
	- createsifter 1.20.1-1.8.1.e-22
	- creativecore 2.11.22
	- cristellib 1.1.5
	- culinaryconstruct 5.2.1+1.20.1
	- cumulus_menus 1.20.1-1.0.0-neoforge
	- cupboard 1.20.1-2.2
	- curios 5.5.0+1.20.1
	- darksmelting 1.0.5
	- dcintegration 3.0.5
	- decorative_blocks 4.0.2
	- design_decor 0.1.0
	- diagonalblocks 8.0.2
	- diagonalfences 8.1.3
	- difficult_caves 1.0.0
	- distinguishedpotions 8.0.2
	- divine_weaponry 1.6.0
	- doggytalents 1.18.7
	- domum_ornamentum 1.20-1.0.110-RELEASE
	- dont_void_arrows 1.0.0
	- doubledoors 5.2
	- drawerstooltip 8.0.0
	- dungeoncrawl 2.3.14
	- durabilitytooltip 1.1.5
	- dynamiclights 1.7.1+mod
	- eatinganimation 5.0.0
	- elytraslot 6.3.0+1.20.1
	- embeddium 0.2.18+mc1.20.1
	- emi 1.1.0+1.20.1+forge
	- emi_loot 0.6.5+1.20.1+forge
	- emitrades 1.2.1+mc1.20.1
	- enchantment_reveal 1.0.0
	- enchdesc 17.0.13
	- enderchests 1.20.1-1.2
	- endrem 5.2.3-R-1.20.1
	- enemyexpansion 2.0.0
	- entityculling 1.6.2
	- essential 1.3.0.2+ge922acc4a7
	- expandability 9.0.0
	- explorify 1.3.0-mc1.20
	- farmersdelight 1.20.1-1.2.3
	- farsight_view 1.20.1-3.6
	- fastasyncworldsave 1.20.1-1.4
	- fasterladderclimbing 0.2.10
	- fastleafdecay 31
	- fastload 3.4.0
	- fastsuite 5.0.1
	- ferritecore 6.0.1
	- findme 3.1.1
	- firstperson 2.3.0
	- flib 0.0.11
	- flowerpatch 3.1.0
	- flywheel 0.6.10-7
	- forge 47.2.19
	- forgeendertech 11.1.0.1
	- forgivingvoid 10.0.0
	- framework 0.6.16
	- friendsandfoes 2.0.7
	- ftbchunks 2001.2.5
	- ftbessentials 2001.2.2
	- ftblibrary 2001.1.4
	- ftbteams 2001.1.4
	- fusion 1.1.0c
	- gateways 4.2.3
	- geckoanimfix 1.0.0
	- geckolib 4.4
	- getittogetherdrops 1.3
	- glassbreaker 1.4.0
	- gml 4.0.9
	- goblintraders 1.9.3
	- golemsarefriends 1.20.0-1.0.1
	- gpumemleakfix 1.20.1-1.8
	- grapplemod 1.20.1-v13
	- guardvillagers 1.20.1-1.6.3
	- harvestwithease 8.0.1.0
	- havendaydisplay 1.0.1
	- hunter_slime 1.0.0
	- immediatelyfast 1.2.8+1.20.4
	- immersive_armors 1.6.1+1.20.1
	- infinitetrading 4.3
	- infwithmend 1.0.2
	- insanelib 1.12.1
	- inventorysorter 23.0.1
	- inventorytotem 3.2
	- ironchest 1.20.1-14.4.4
	- irons_spellbooks 1.20.1-2.2.1
	- ite 1.0
	- itemproductionlib 1.0.0a
	- jade 11.7.1
	- jadeaddons 5.2.2
	- jei 15.2.0.27
	- jeresources 1.4.0.238
	- jumpboat 1.20.0-1.0.5
	- kambrik 6.1.1+1.20.1
	- keepmysoiltilled 2.2
	- kotlinforforge 4.10.0
	- krypton 0.2.3
	- lazulib 1.2.0
	- leaky 1.20.1-1.7
	- letmedespawn 1.2.0
	- lightoverlay 8.0.0
	- limitedchunks 1.8
	- lootr 0.7.29.68
	- luphieclutteredmod 2.1
	- magistuarmory 8.11
	- majruszlibrary 7.0.3
	- majruszsaccessories 1.4.0
	- majruszsdifficulty 1.9.6
	- maxhealthfix 12.0.2
	- mcwbridges 2.1.1
	- mcwdoors 1.1.0
	- mcwfences 1.1.0bb
	- mcwfurnitures 3.2.2
	- mcwroofs 2.2.4b
	- mcwtrpdoors 1.1.2
	- mcwwindows 2.2.1
	- minecraft 1.20.1
	- mixinextras 0.3.2
	- mixinsquared 0.1.1
	- mob_grinding_utils 1.20.1-1.0.3
	- modelfix 1.14
	- modernfix 5.12.1+mc1.20.1
	- molten_vents 2.0.6
	- monster_hunter_villager 1.1.0
	- moonlight 1.20-2.8.84
	- moremobvariants 1.2.2
	- mousetweaks 2.25
	- mr_caves__canyons 1.2
	- mr_dungeons_andtaverns 3.0.3
	- mr_stellarity 2.0d
	- mutantmonsters 8.0.6
	- mutil 6.1.1
	- naturescompass 1.20.1-1.11.2-forge
	- neruina 1.3.0
	- netherportalfix 13.0.1
	- netherrackblasting 1.20.1-0-forge
	- nethersdelight 1.20.1-4.0
	- nitrogen_internals 1.20.1-1.0.1-neoforge
	- no_nv_flash 1.6.0
	- noincreasingrepaircost 1.0.0
	- notenoughanimations 1.7.0
	- notenoughcrashes 4.4.7+1.20.1
	- obscure_api 15
	- octolib 0.1
	- oculus 1.6.13
	- onlyexcavators 1.20.1-0.1
	- onlyhammers 1.20.1-0.3
	- oregrowth 1.0.11
	- patchouli 1.20.1-84-FORGE
	- pathtodirt 1.7.3-mc1.20.1
	- piercearrow 1.20.1-5.0.0
	- pingwheel 1.7.1
	- placebo 8.6.0
	- playeranimator 1.0.2-rc1+1.20
	- playershops 1.1.2
	- polymorph 0.49.2+1.20.1
	- pots_and_mimics 1.0.2
	- presencefootsteps 1.20.1-1.9.1-beta.1
	- prettypipes 1.15.0
	- progressivebosses 3.9.5-mc1.20.1
	- puzzlesaccessapi 8.0.7
	- puzzleslib 8.1.13
	- railways 1.5.3+forge-mc1.20.1
	- ramcompat 0.1.0.2
	- realmrpg_creep 1.0.2
	- realmrpg_demons 0.9.0
	- realmrpg_skeletons 1.0.3
	- recipeessentials 1.20.1-3.2
	- relics 0.5.2.1
	- resourcefulconfig 2.1.2
	- resourcefullib 2.1.20
	- responsiveshields 2.3
	- riverredux 0.3.1
	- rubidium 0.7.1
	- sapience 1.20.1-1.0.0
	- saturn 0.1.2
	- scalinghealth 8.0.1+8
	- scena 1.0.103
	- searchables 1.0.2
	- secondchanceforge 1.5.1
	- sereneseasons 9.0.0.46
	- shetiphiancore 1.20.1-1.2
	- shouldersurfing 1.20.4-2.8.2
	- silentlib 8.0.0
	- simplyswords 1.51.5-1.20.1
	- skinlayers3d 1.6.2
	- sliceanddice 3.2.0
	- smarterfarmers 1.20-1.8.0
	- smoothboot 0.0.4
	- smoothchunk 1.20.1-3.5
	- sophisticatedbackpacks 3.19.5.988
	- sophisticatedcore 0.5.113.524
	- sound_physics_remastered 1.20.1-1.3.1
	- spark 1.10.53
	- spectrelib 0.13.14+1.20.1
	- spelunkery 1.20.1-0.3.5
	- spruceui 0.1.2+1.20.1
	- stackablepotions 1.0.0
	- stackrefill 4.2
	- stalwart_dungeons 1.2.8
	- starbunclemania 1.20.1-1.2.0.7
	- stoneworks 8.0.0
	- storagedrawers 12.0.2
	- storageracks 1.20.1-1.7
	- structory 1.3.4
	- structure_gel 2.16.0
	- structureessentials 1.20.1-3.2
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.16
	- supplementaries 1.20-2.7.27
	- t_and_t 0.0NONE
	- terrablender 3.0.1.2
	- tetra 6.1.0
	- the_bumblezone 7.2.2+1.20.1-forge
	- timestacker 1.1.2.1
	- toastcontrol 8.0.3
	- togenc 1.0
	- tombstone 8.6.0
	- toms_storage 1.6.5
	- torchhit 6.0.2.0
	- trade_cycling 1.20.1-1.0.7
	- tradingpost 8.0.1
	- tramplenomore 13.0.2
	- trashslot 15.1.0
	- treasuredistance 1.20-1.2
	- treechop 0.18.3
	- trowelsfork 2.0.0
	- twilightforest 4.3.1893
	- universalbonemeal 8.0.1
	- variablespawnerhardness 1.20-1.4.0
	- vinecollector 1.2.3
	- visualworkbench 8.0.0
	- vivecraft 1.20.1-1.1.5
	- vivecraftcompat 1.3.1
	- w2pets 1.0
	- w2w2 1.0
	- wallets 1.1.0
	- walljump 1.20.1-1.1.4-forge
	- waterdripsound 0.3.2
	- watut 1.20.1-1.0.13
	- waystones 14.1.3
	- wooledboots 1.7.1
	- wooltostring 1.1.0
	- wrd 2.0.0
	- xaerominimap 23.9.3
	- xaeroworldmap 1.37.2
	- yungsapi 1.20-Forge-4.0.2

**Logs:**
*Even if the game does not crash they may be useful!*
[latest.log](https://github.com/AstralOrdana/Spelunkery/files/14000255/latest.log)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1.Find spring water
or
2.Place from bucket

**Expected behavior:**
for it to work like water

**Screenshots:**
![Minecraft Forge_ 1 20 1 - Singleplayer 1_20_2024 11_32_25 PM](https://github.com/AstralOrdana/Spelunkery/assets/157267749/895bdd0d-318b-49cb-86ff-dacdd3fed924)

**Comment by AstralOrdana** [comment] 2024-02-23 01:28
working as intended, it is meant to buttow upward through blocks like a geyser

**Comment by MarioSMB** [comment] 2024-03-07 17:54
Intended as it may be, it is extremely odd-looking to have random pillars of water throughout the world going all the way up to the height limit.  
I hope you can reconsider improving the design of spring water to better fit into the game.  

EDIT: At the very least can we get an option/gamerule to disable this behaviour? It's nearly impossible to get rid of them once they form!

**Comment by AstralOrdana** [comment] 2024-03-07 18:34
my bad, i misinterpreted what the issue here was. 
the spring water is coded to only burrow through blocks in the `OVERWORLD_CARVER_REPLACEABLES` as seen [here](https://github.com/AstralOrdana/Spelunkery/blob/1.20.1/forge/src/main/java/com/ordana/spelunkery/forge/SpringWaterBlock.java#L41)
its possible that one of the mods in that modlist adds air to that tag or modifies it in some other way 

reopening until properly resolved

**Comment by MarioSMB** [comment] 2024-03-07 18:58
... You're right, it's Wesley's Roguelike Dungeons. That is extremely weird of them, I'll let them know they shouldn't be doing that.  
In the meantime, maybe spring water should avoid trying to replace air as well as a safety measure?  

EDIT: In my case it was the Wesley mod but given that is not in their list it seems a few mods are doing this - maybe it's a MCreator thing? Probably best to just assume the tag can possibly be empty or have air and have a safety fallback anyway!

**Comment by abby-cadabra** [comment] 2024-06-06 05:35
Came here to see if anyone else has this issue. I just installed Wesley's as well, so guessing that's the culprit. Extremely weird and I can't seem to find any way to get rid of the water pillars, even in Creative.

**Comment by MarioSMB** [comment] 2024-06-06 05:53
I did report it to them, but given the overall “quality” of the WRD mod it is unlikely a fix will be added.  
In the meantime a workaround would be a little challenging, as you would have to find all the current blocks in the aforementioned tag and add them into your own in replace mode - or edit the .jar file directly to remove air from the tag (not a great practice but this is a pretty game breaking bug).

**Comment by abby-cadabra** [comment] 2024-06-06 05:56
Damn, I wouldn't have a clue where to even start editing a jar file. Guess I'm going to have to pick which mod I want to run.

**Comment by MarioSMB** [comment] 2024-06-06 06:34
In my experience we never actually got into the roguelike dungeon content, we ended up removing it later on to solve the world gen issues (among other things).  
Spelunkery on the other hand was being interacted with on day one and continued to provide fun little things along the journey.

It’s up to you but I can vouch for this mod!

**Comment by abby-cadabra** [comment] 2024-06-06 06:45
Yeah, I've been running Spelunkery for a while and never tried Wesley's, so it's a fairly easy decision to stick with Spelunkery.

Always looking for new adventure mods but it's not worth breaking one of my favs.

**Comment by TROLEwsky** [comment] 2024-06-22 10:27
Strange, I've never used Wesley's but this problem exists, the water just flows uphill even just from the bucket

**Comment by luoxuan-cs** [comment] 2024-08-11 07:40
Same issue, and it will be fixed after removed Wesley's dungeons.

**Comment by AstralOrdana** [comment] 2024-08-17 02:14
was fixed in 0.3.6

**Closed as completed by AstralOrdana** 2024-08-17 02:14 UTC
