### ISSUE TITLE
0.2.6 Server Parachute Crash

### ISSUE THREAD

**Issue by JAWredstoneguy** [AstralOrdana/Spelunkery#131] opened 2023-09-03 00:14 UTC
**Describe the bug:**
Whenever a player right clicks with a parachute, the other players on the server who are attempting to render the parachute crash.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.19.2
Spelunkery version: 0.2.6
Moonlight Lib version: 2.2.44
Fabric API / QSL / Forge version: Forge version 43.2.21

**Other mods:**
<img width="1140" alt="image" src="https://github.com/AstralOrdana/Spelunkery/assets/107218089/d1f613a7-bb28-40da-90bf-e4d4d7be0d24">

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
From .minecraft/logs :  "latest.log" as well as "debug.log" if it exists. From .minecraft : "launcher_log" as well as a
file that starts with "hs_err" if it exists. Note: Double check that the logs are from the correct time. ex, don't give
us a log from a month ago because you forgot to check the date.

[2023-09-02-7.log](https://github.com/AstralOrdana/Spelunkery/files/12504896/2023-09-02-7.log)
[launcher_log.txt](https://github.com/AstralOrdana/Spelunkery/files/12504907/launcher_log.txt)

**To Reproduce:**

1.Install Spelunkery 0.2.6 on a server with other people
2.Right click on a parachute while falling from a decent height with players within render distance

**Expected behavior:**
The parachute should render for other players without crashing them

**Additional info:**
the parachute does not render for other players if it is auto deployed, but it also does not crash them.

**Comment by AstralOrdana** [comment] 2024-02-23 01:36
duplicate of #143

**Closed by AstralOrdana** 2024-02-23 01:36 UTC
