### ISSUE TITLE
Dimensional tears visual bug

### ISSUE THREAD

**Issue by ShadowMaster1717** [AstralOrdana/Spelunkery#216] opened 2024-05-04 22:03 UTC
The North and South textures for the dimensional tears liquid do not have a texture. 
![image](https://github.com/AstralOrdana/Spelunkery/assets/168937860/babc4ac0-82c2-4bf1-bd3b-4e046ed79c3c)

Minecraft version: 1.20.1
Spelunkery version: 0.3.5
Moonlight Lib version: 2.11.14
Fabric API / QSL / Forge version: Forge 47.2.0

**Other mods:**
List all mods that you're using; could be in the form of a list of the filenames, a crash report list, a screenshot of
the mods folder, etc. Just make sure all mods used are known!

Not a crash, 
*Even if the game does not crash they may be useful!*
I could not find launcher_loga or a file that starts with "hs_er
[latest.log](https://github.com/AstralOrdana/Spelunkery/files/15211067/latest.log)
![2024-05-04_17 55 06](https://github.com/AstralOrdana/Spelunkery/assets/168937860/070dd729-01e3-41f9-893f-9e41a397f8cf)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Install the mods listed/maybe just the mod at that version.
2.Get a 3x3 pool of dimensional tears surrounded by solid blocks.
3. Look at the north and south edges, which should be without a texture.

**Expected behavior:**
I expected there to be the normal edge texture there, instead of a glitch checkerboard.

**Screenshots:**
I did :)

**Additional info:**
:) have a great day, i love this mod :)

**Comment by ShadowMaster1717** [comment] 2024-05-04 22:05
Oh wait forgot to list the mods. They won't show up in the folder, so here is a version of the modpack (curseforge). A beefy pc is advised.
[Fun RPG (1) (2) (1) (1) (1).zip](https://github.com/AstralOrdana/Spelunkery/files/15211072/Fun.RPG.1.2.1.1.1.zip)

**Comment by AstralOrdana** [comment] 2024-05-07 02:43
duplicate of https://github.com/AstralOrdana/Spelunkery/issues/135

**Closed as completed by AstralOrdana** 2024-05-07 02:43 UTC
