### ISSUE TITLE
Parachute crashing the game when viewed in 3rd person. [Quilt]

### ISSUE THREAD

**Issue by LazyKitch** [AstralOrdana/Spelunkery#98] opened 2023-07-26 02:16 UTC
**Describe the bug:**
Viewing your character in 3rd-person while using a parachute momentarily freezes and then crashes the game.

Minecraft version: Minecraft 1.19.2
Spelunkery version: spelunkery-1.2.19.2-0.2.4-fabric
Moonlight Lib version: moonlight-1.19.2-2.2.43-fabric
Fabric API / QSL / Forge version: qfapi-4.0.0-beta.30_qsl-3.0.0-beta.29_fapi-0.76.0_mc-1.19.2

**Other mods:**
supplementaries-1.19.2-2.3.20-fabric.jar

**Logs:**
[launcher_log.txt](https://github.com/AstralOrdana/Spelunkery/files/12167082/launcher_log.txt)
[crash-2023-07-25_18.33.38-client.txt](https://github.com/AstralOrdana/Spelunkery/files/12167083/crash-2023-07-25_18.33.38-client.txt)
[latest.log](https://github.com/AstralOrdana/Spelunkery/files/12167084/latest.log)

**To Reproduce:**
1. Deploy a parachute while falling.
2. Press F5 to enter a 3rd-person perspective.

**Comment by AstralOrdana** [comment] 2023-07-26 02:18
duplicate of #94

**Closed by AstralOrdana** 2023-07-26 02:18 UTC
