### ISSUE TITLE
North - south "line" texture of dimensional tears liquid is missing

### ISSUE THREAD

**Issue by CwumbTheCrumb** [AstralOrdana/Spelunkery#238] opened 2024-06-28 08:40 UTC
**Describe the bug:**
North - south "line" texture of dimensional tears liquid is missing

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: 0.3.5
Moonlight Lib version: 2.12.6
Fabric API / QSL / Forge version: 47.2.17, forge

**Other mods:**
this occurs with just spelunkery (and it's libs)

**Logs:**
not nessesarry

**To Reproduce:**

1. find obsidian lake (no idea how it's called, sorry) in the end OR grab a bucket of dimensional tears from creative
2. make a pool alike in screenshot above
3. enjoy not installed cs source moment xd

**Expected behavior:**
linear texture appearing properly

**Screenshots:**
![2024-06-28_11 38 16](https://github.com/AstralOrdana/Spelunkery/assets/99805855/f0f01f31-94d6-4032-8790-c9f18dc319f0)

**Additional info:**
sorry for bad english, me silly :3

**Comment by KMaxK9** [comment] 2024-07-10 11:16
I have the same Issue since last week.

**Comment by Luningor** [comment] 2024-07-18 01:12
Can attest this happens on my side too. I even checked to see if the assets were there, and they were fine too. Dunno what's it about.

**Comment by Qwerty97475** [comment] 2024-07-18 02:03
some other people and I are also having this issue 
![2024-07-18_14 00 14](https://github.com/user-attachments/assets/4a5928ed-dafc-49ab-b733-502de584c208)

**Comment by AstralOrdana** [comment] 2024-07-18 02:04
yet another duplicate of https://github.com/AstralOrdana/Spelunkery/issues/135

**Closed as completed by AstralOrdana** 2024-07-18 02:04 UTC
