### ISSUE TITLE
[1.20.1] Dimensional Tears facing north/south break

### ISSUE THREAD

**Issue by Reshy** [AstralOrdana/Spelunkery#169] opened 2024-01-24 06:26 UTC
**Describe the bug:**
If a piece of dimensional tears spawns with a north/south (no corner pieces) the graphic is replaced with a errored out texture.

**Versions: 
Minecraft version:  1.20.1
Spelunkery version:  spelunkery-1.20.1-0.3.5-forge.jar
Moonlight Lib version:  moonlight-1.20-2.9.3-forge.jar
Fabric API / QSL / Forge version:  47.2.6

**Other mods:**
![image](https://github.com/AstralOrdana/Spelunkery/assets/2096384/342827b1-5a93-4285-b964-5c7b9bcea44b)

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs: https://pastebin.com/nPiFcmwS

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1.  Install Iris and Spelunkery simultaneously.
2.  Place down a 3x3 grid of dimensional tears.
3.  The North/South facing walls will error out.

**Expected behavior:**
The graphics shouldn't be breaking just by having iris installed.

**Screenshots:**
Without Iris:
![2024-01-23_22 21 10](https://github.com/AstralOrdana/Spelunkery/assets/2096384/8b1a5c70-d706-41af-83b8-f96e9d6569b3)

With Iris:
![2024-01-23_22 26 09](https://github.com/AstralOrdana/Spelunkery/assets/2096384/c4299ba0-14b4-4c3f-8e3e-e79f544789d7)

**Comment by AstralOrdana** [comment] 2024-01-24 06:28
this is a known issue caused by iris, we have no idea why though

**Comment by Reshy** [comment] 2024-01-24 06:37
Have you tried contacting the people behind iris to see if they have encountered anything similar before in another mod?

**Comment by SiverDX** [comment] 2024-01-24 08:35
this can be fixed by adding the following file to the resources

path: `assets\minecraft\atlases\blocks.json`

```json
{
    "sources": [
        {
            "type": "single",
            "resource": "spelunkery:block/portal_fluid_n"
        },
        {
            "type": "single",
            "resource": "spelunkery:block/portal_fluid_s"
        }
    ]
}
```

i think it might be a hit or miss if the textures are in the atlas if they're not being referenced by any model
(which is the case for (most) of the portal fluid textures)

**Comment by AstralOrdana** [comment] 2024-01-24 17:41
Thats inredible, that worked! tysm, this fix will be included in the next spelunkery release (no eta at the moment)

**Closed as completed by AstralOrdana** 2024-01-24 17:41 UTC
