### ISSUE TITLE
Crash when loading world or exploring world

### ISSUE THREAD

**Issue by Specimen-420** [AstralOrdana/Spelunkery#141] opened 2023-09-24 14:59 UTC
**Describe the bug:**
Game crashes when either when loading into a world or when loading specific chunks

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: 0.3.4
Moonlight Lib version: 2.8.28
QSL: 6.1.2

**Other mods:**
List all mods that you're using; could be in the form of a list of the filenames, a crash report list, a screenshot of
the mods folder, etc. Just make sure all mods used are known!

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:

Crash Report: https://mclo.gs/9zVuahl
Log: https://mclo.gs/gl4KKS9

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. open or create new world
2. if you havent crashed yet explore new chunks untill you do

**Expected behavior:**
Game should crash

**Comment by SiverDX** [comment] 2023-09-24 15:05
Same issue as https://github.com/AstralOrdana/Spelunkery/issues/112

**Comment by AstralOrdana** [comment] 2023-12-09 21:48
duplicate of https://github.com/AstralOrdana/Spelunkery/issues/112#issue-1850979142

**Closed by AstralOrdana** 2023-12-09 21:48 UTC
