### ISSUE TITLE
Missing Textures on Dimensional Tears Liquid

### ISSUE THREAD

**Issue by AzrannAVANA** [AstralOrdana/Spelunkery#214] opened 2024-05-02 22:05 UTC
**Describe the bug:**
I seem to be missing sides of the Dimensional Tears texture... Maybe an incompatibility.
![image](https://github.com/AstralOrdana/Spelunkery/assets/112041895/c9be6edd-c345-4f92-aeca-668a754dd0ed)

**Versions:**
Minecraft version: 1.20.1
Spelunkery version: 1.20.1-0.3.5
Moonlight Lib version: forge_1.20-2.11.14
Forge version: 1.20.1-47.2.17

**Other mods:**
[modlist latest.txt](https://github.com/AstralOrdana/Spelunkery/files/15194455/modlist.latest.txt)

**Logs:**

[debug.log](https://github.com/AstralOrdana/Spelunkery/files/15194464/debug.log)

[latest.log](https://github.com/AstralOrdana/Spelunkery/files/15194473/latest.log)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Have a similar modlist to mine
2. Find any sort of pool of Dimensional Tears
3. Observe missing textures.

**Expected behavior:**
Textures should not be missing.

**Screenshots:**
![image](https://github.com/AstralOrdana/Spelunkery/assets/112041895/f14342bd-992c-4182-99bf-5bebd47c3978)

**Additional info:**
I am sorry for adding so many mods-

**Comment by AzrannAVANA** [comment] 2024-05-02 22:05
Oh, sorry right, the faces missing are North & South here.

**Comment by AstralOrdana** [comment] 2024-05-03 02:34
duplicate of https://github.com/AstralOrdana/Spelunkery/issues/135

**Closed as completed by AstralOrdana** 2024-05-03 02:34 UTC

**Comment by AzrannAVANA** [comment] 2024-05-03 14:14
Oh sorry, I looked up Dimensional Tears but found nothing, so a- Thanks!
